### ISSUE TITLE
Unable to select a SSO provider

### ISSUE THREAD

**Issue by BenB196** [jlesage/docker-crashplan-enterprise#1]
I am testing out this docker container to run on some Linux servers. However it does not appear to allow me to select a Single Sign-On provider after I type in my email address as the list is empty.

![image](https://user-images.githubusercontent.com/8277432/53834091-2875ee00-3f58-11e9-99d4-f2afc33059c8.png)

Image: jlesage/crashplan-enterprise:latest
Docker command: docker run -d --name=crashplan-enterprise -p 5800:5800 -v /crashplan:/config:rw -v /elastic-stack:/storage:ro jlesage/crashplan-enterprise:latest

I am using Crashplan Enterprise Cloud.

Also I don't know if this has anything to do with it, but it seems like the client is the Small Business client.

![image](https://user-images.githubusercontent.com/8277432/53834333-bb168d00-3f58-11e9-9669-01d8e3bb12fc.png)

**Comment by jlesage** [comment]
Could you provide the URL of the Linux package?  I can verify if it's the same as the one used in this image.

**Comment by BenB196** [comment]
I was actually able to get this to work. For some reason I need to completely delete the folder that was being mounted as /config and recreate it, idk what was causing the issue, but that seemed to fix it.
