### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by riccanet** [jlesage/docker-crashplan-enterprise#3]
I'm not sure where to even start with the troubleshooting. My QNAP container connected fine initially to Code42 then backs upthe config folder, but my online console keeps saying the device is offline. I need to replace another device and I keep getting cannot connect to server. I was previously running the QPKG and it was functional until the latest update.

![image](https://user-images.githubusercontent.com/33169580/59965245-74ce4500-94d9-11e9-878a-b8d3cfa9d7fc.png)

docker command I used:
docker run -d \
    --name=Code42-Crashplan \
    -v /docker/appdata/crashplan-enterprise:/config:rw \
    -v $HOME:/storage:ro \
    -e USER_ID=0 \
    -p 5800:5800 \
    -e GROUP_ID=0 \
    -p 5900:5900 \
    -e TZ=America/New_York \
    -e CRASHPLAN_SRV_MAX_MEM=1024M \
    -v /share/CACHEDEV1_DATA:/share:ro \
    jlesage/crashplan-enterprise

**Comment by jlesage** [comment]
I would start by looking at the following log file : `/docker/appdata/crashplan-enterprise/log/service.log.0`.

**Comment by riccanet** [comment]
Thanks I opened up a ticket with Code42. Its very odd that it gets through the whole process connects to the account then all the sudden can't connect. The log pretty much says that CPC is unavailable.

**Comment by riccanet** [comment]
Just loaded your latest image with Crashplan 7.0 and it fixed the issue. Thank you.
