### ISSUE TITLE
Cannot add folder to backup with Manage Files

### ISSUE THREAD

**Issue by r-b-n** [jlesage/docker-crashplan-enterprise#4]
Hi
I am using this version on a Synology device. It does seem to be able to backup all the files in the root folder.
But even after adding a volume to the docker and adding the path /storage and making sure the Docker user is a user with read and write permission to that folder it does not show the folder in the Manage Files menu in Code42 app.

Am I missing somthing here?

//Robin

**Comment by jlesage** [comment]
Can you share the output of `docker inspect <container name>` ?

**Comment by r-b-n** [comment]
Hi
Sorry but not sure how to do that?

I have not been running this with any terminal commands. Only gui installation on Synology.

But if you can send some more info on what you want me to do and I am more than willing to to whatever you need me to :)

//rbn
______________________________

**Comment by jlesage** [comment]
This command can be run from the terminal.  If it's easier for you can could also share your container configuration using screenshots.

**Comment by r-b-n** [comment]
Realised it was as easy as SSH into the Synology :)

Here is the output for that command:

[
    {
        "Id": "2e8f4d2a9bd7649c03be2fa66994e5e8becabc71c40c95dbed28eb9767518787",
        "Created": "2020-11-11T15:11:09.551328631Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 8786,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-11-14T08:50:48.034168879Z",
            "FinishedAt": "2020-11-13T13:13:25.837753881Z",
            "StartedTs": 1605343848,
            "FinishedTs": 1605273205
        },
        "Image": "sha256:c156b27000b9ddc200a5cd7049496106380285ee3a0b24edc58614d74749264a",
        "ResolvConfPath": "/volume2/@docker/containers/2e8f4d2a9bd7649c03be2fa66994e5e8becabc71c40c95dbed28eb9767518787/resolv.conf",
        "HostnamePath": "/volume2/@docker/containers/2e8f4d2a9bd7649c03be2fa66994e5e8becabc71c40c95dbed28eb9767518787/hostname",
        "HostsPath": "/volume2/@docker/containers/2e8f4d2a9bd7649c03be2fa66994e5e8becabc71c40c95dbed28eb9767518787/hosts",
        "LogPath": "/volume2/@docker/containers/2e8f4d2a9bd7649c03be2fa66994e5e8becabc71c40c95dbed28eb9767518787/log.db",
        "Name": "/CopyCloud",
        "RestartCount": 0,
        "Driver": "aufs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/NasFolder:/storage:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": ""
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=100",
                "GROUP_ID=1000",
                "APP_NAME=CrashPlan Enterprise",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 50,
            "Memory": 1073741824,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 2147483648,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/NasFolder",
                "Destination": "/storage",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "a86c4414e4c9af5319a644bd120a71382907ee461080f9ec128ab73bd39fbb57",
                "Source": "/volume2/@docker/volumes/a86c4414e4c9af5319a644bd120a71382907ee461080f9ec128ab73bd39fbb57/_data",
                "Destination": "/config",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "CopyCloud",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=100",
                "GROUP_ID=1000",
                "APP_NAME=CrashPlan Enterprise",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1"
            ],
            "Cmd": [
                "/init"
            ],
            "Image": "jlesage/crashplan-enterprise:latest",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2020-10-29T21:47:02Z",
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-enterprise",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "3bee9c185f914fdf54e6a91d53cc7d90e59b534a",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-enterprise.git",
                "org.label-schema.version": "1.7.1"
            },
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "913655d696742c3d12d057728b83c4568404e6a3b80df8b855344a7eed77a540",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32785"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32784"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/913655d69674",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "0784a644d5427ac0c529a1a5a6ea35beab14bbc43aa7f3441e9fbd3170210249",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2a25d7cfae2de0d7b2f2b2bdd61817aab7937bd27827e059fc3148f737c3efd0",
                    "EndpointID": "0784a644d5427ac0c529a1a5a6ea35beab14bbc43aa7f3441e9fbd3170210249",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

//Robin
______________________________

**Comment by jlesage** [comment]
So currently, it seems that the only configured volume is `/volume1/NasFolder`, mapped to `/storage` in the container.  Is it what you expect ?

**Comment by r-b-n** [comment]
Hi
Yes. In FileStation on the synology I have a Folder called NasFolder. And yes it is on volume1

But CrashPlan does not see this folder. It only sees the system folder of the Synology unit. 

//Robin
----------

**Comment by jlesage** [comment]
From the CrashPlan UI, are you looking at `/storage` (i.e. **not** `/volume1/NasFolder`)?

**Comment by r-b-n** [comment]
Hi
If I click manage files I see root folder


And then if I click that I see the systems folder. I checked in those as well, but cannot see any folder named NasFolder or anything else (checked mnt and folders like that.).



//Robin
______________________________

**Comment by jlesage** [comment]
Can you provide the output of:
```
docker exec <container name> ls -l /
```

**Comment by r-b-n** [comment]
Yes, this is the output.

drwxr-xr-x    2 root     root          4096 Nov 11 15:30 Volumes
drwxr-xr-x    2 root     root          4096 Oct 29 21:48 bin
drwxr-xr-x   12 app      app           4096 Nov 16 15:27 config
drwxr-xr-x    3 root     root          4096 Oct 29 21:48 defaults
drwxr-xr-x   10 root     root         18700 Nov 14 08:50 dev
drwxr-xr-x   81 root     root          4096 Nov 14 08:50 etc
drwxr-xr-x    2 root     root          4096 Jun 26 02:56 home
-rwxr-xr-x    1 root     root           389 Mar  1  2018 init
drwxr-xr-x   20 root     root          4096 Oct 29 21:48 lib
drwxr-xr-x    2 root     root          4096 Jun 26 02:56 lib64
drwxr-xr-x    2 root     root          4096 Mar  1  2018 libexec
drwxr-xr-x    5 root     root          4096 Jan 23  2020 media
drwxr-xr-x    2 root     root          4096 Jan 23  2020 mnt
drwxr-xr-x    9 root     root          4096 Nov 11 15:11 opt
dr-xr-xr-x  305 root     root             0 Nov 14 08:50 proc
drwx------    2 root     root          4096 Jan 23  2020 root
drwxr-xr-x    4 root     root          4096 Nov 14 08:51 run
drwxr-xr-x    2 root     root          4096 Oct 29 21:48 sbin
drwxr-xr-x    2 root     root          4096 Jan 23  2020 srv
-rwxr-xr-x    1 root     root           650 Oct 29 21:46 startapp.sh
d---------    1 root     root            64 Nov 11 12:41 storage
dr-xr-xr-x   12 root     root             0 Nov 14 08:50 sys
drwxrwxrwt    7 root     root          4096 Nov 14 08:51 tmp
drwxr-xr-x   85 root     root          4096 Nov 11 15:11 usr
drwxr-xr-x   32 root     root          4096 Nov 11 15:11 var

Looks like we don’t have permission to se storage… right? But how is that possible. Because it looks like NO User has rights to it … hm.

//Robin
______________________________

**Comment by jlesage** [comment]
Do the folder has proper permissions on your NAS ?
```
ls -l /volume1/
```

**Comment by r-b-n** [comment]
Looks like it:

ls -l /volume1/
total 0
drwxr-xr-x  1 admin users 76 Oct 29 10:27 @database
drwxrwxrwx+ 1 root  root  42 Oct 31 16:56 @eaDir
drwxrwxrwx+ 1 root  root  64 Nov 11 13:41 NasFolder
drwxr-xr-x  1 root  root  24 Oct 29 10:27 @S2S
drwxr-xr-x  1 root  root  84 Oct 31 16:56 @SynoFinder-log
drwxrwxrwt  1 root  root  34 Nov 11 14:01 @tmp

If I change the volume mount path setting on the docker installation from /storage to /mnt this is how the ls changes:

drwxr-xr-x    2 root     root          4096 Nov 11 15:30 Volumes
drwxr-xr-x    2 root     root          4096 Oct 29 21:48 bin
drwxr-xr-x   12 app      app           4096 Nov 16 17:39 config
drwxr-xr-x    3 root     root          4096 Oct 29 21:48 defaults
drwxr-xr-x   10 root     root         18700 Nov 16 17:38 dev
drwxr-xr-x   81 root     root          4096 Nov 16 17:38 etc
drwxr-xr-x    2 root     root          4096 Jun 26 02:56 home
-rwxr-xr-x    1 root     root           389 Mar  1  2018 init
drwxr-xr-x   20 root     root          4096 Oct 29 21:48 lib
drwxr-xr-x    2 root     root          4096 Jun 26 02:56 lib64
drwxr-xr-x    2 root     root          4096 Mar  1  2018 libexec
drwxr-xr-x    5 root     root          4096 Jan 23  2020 media
d---------    1 root     root            64 Nov 11 12:41 mnt
drwxr-xr-x    9 root     root          4096 Nov 11 15:11 opt
dr-xr-xr-x  310 root     root             0 Nov 16 17:38 proc
drwx------    2 root     root          4096 Jan 23  2020 root
drwxr-xr-x    4 root     root          4096 Nov 16 17:38 run
drwxr-xr-x    2 root     root          4096 Oct 29 21:48 sbin
drwxr-xr-x    2 root     root          4096 Jan 23  2020 srv
-rwxr-xr-x    1 root     root           650 Oct 29 21:46 startapp.sh
drwxr-xr-x    2 root     root          4096 Nov 11 15:11 storage
dr-xr-xr-x   12 root     root             0 Nov 16 17:38 sys
drwxrwxrwt    7 root     root          4096 Nov 16 17:38 tmp
drwxr-xr-x   85 root     root          4096 Nov 11 15:11 usr
drwxr-xr-x   32 root     root          4096 Nov 11 15:11 var

As you can see now the mnt is blocked

//Robin
______________________________

**Comment by r-b-n** [comment]
If I change the mount path to /volume1/NasFolder it gets like this:

drwxr-xr-x    2 root     root          4096 Nov 11 15:30 Volumes
drwxr-xr-x    2 root     root          4096 Oct 29 21:48 bin
drwxr-xr-x   12 app      app           4096 Nov 16 17:44 config
drwxr-xr-x    3 root     root          4096 Oct 29 21:48 defaults
drwxr-xr-x   10 root     root         18700 Nov 16 17:44 dev
drwxr-xr-x   81 root     root          4096 Nov 16 17:44 etc
drwxr-xr-x    2 root     root          4096 Jun 26 02:56 home
-rwxr-xr-x    1 root     root           389 Mar  1  2018 init
drwxr-xr-x   20 root     root          4096 Oct 29 21:48 lib
drwxr-xr-x    2 root     root          4096 Jun 26 02:56 lib64
drwxr-xr-x    2 root     root          4096 Mar  1  2018 libexec
drwxr-xr-x    5 root     root          4096 Jan 23  2020 media
drwxr-xr-x    2 root     root          4096 Jan 23  2020 mnt
drwxr-xr-x    9 root     root          4096 Nov 11 15:11 opt
dr-xr-xr-x  310 root     root             0 Nov 16 17:44 proc
drwx------    2 root     root          4096 Jan 23  2020 root
drwxr-xr-x    4 root     root          4096 Nov 16 17:44 run
drwxr-xr-x    2 root     root          4096 Oct 29 21:48 sbin
drwxr-xr-x    2 root     root          4096 Jan 23  2020 srv
-rwxr-xr-x    1 root     root           650 Oct 29 21:46 startapp.sh
drwxr-xr-x    2 root     root          4096 Nov 11 15:11 storage
dr-xr-xr-x   12 root     root             0 Nov 16 17:44 sys
drwxrwxrwt    7 root     root          4096 Nov 16 17:44 tmp
drwxr-xr-x   85 root     root          4096 Nov 11 15:11 usr
drwxr-xr-x   32 root     root          4096 Nov 11 15:11 var
drwxr-xr-x    3 root     root          4096 Nov 16 17:44 volume1

But I still cannot see it in the CrashPlan app.

But also… if I run
ls -l /volume1/

I get:

d---------    1 root     root            64 Nov 11 12:41 NasFolder

So it sure lockes the mount path somehow.

//Robin
______________________________

**Comment by r-b-n** [comment]
Hi again
I noticed I could see the folder in Manage files under /volume1/NasFolder. It is selected, but I cannot see any sub folders in it. So some sort of permission error is it. At least I can see it … that’s progress.

//Robin
______________________________

**Comment by r-b-n** [comment]
FOUND IT.

Somehow I must have put in the group ID on the user ID running the docker app. Now when I changed it I was able to see the volumes as expected.

Thank you so much for assisting me… it sometimes is easier to find the problem when having someone else to test with.

//Robin
______________________________

**Comment by jlesage** [comment]
Great, glad to see that you found the issue :)
